spring:
  profiles:
    active: local
    group:
      local:
        - s3
        - db
      # dev
      # prod

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    database: mysql
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
  banner:
    location:

scheduler:
  cron:
    matches:
      confirm: "0 0 0/1 * * *"

address-api:
  key: devU01TX0FVVEgyMDIzMTEwODIyMjIxOTExNDI1NzI=