cloud:
  aws:
    credentials:
      access-key: AKIAWB7WP7DSKWSZCRKQ
      secret-key: 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
    s3:
      bucket: racket-puncher
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false