spring:
  profiles:
    active: local
    group:
      local:
        - s3
        - db
      # dev
      # prod

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    database: mysql
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
